routes/web.php
<?php

use App\Http\Controllers\Backend\UserController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Backend\ChangePasswordController;
use App\Http\Controllers\Backend\EmployeesController;
use App\Http\Controllers\Backend\RolesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/login', function () {
    return view('login');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/users',UserController::class);
Route::post('users/{user}/change-password',[ChangePasswordController::class,'change_password'])->name('users.change.password');
Route::resource('/roles',RolesController::class);

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $fillable = [
        'name'
    ];
  public function users(){
      return $this->belongsToMany('App\Models\User');
  }
    
}

app/Http/Controllers/Backend/RolesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Http\Requests\RoleStoreRequest;
use App\Http\Requests\RoleUpdateRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;


class RolesController extends Controller
{
    public function index(Request $request)
    {
        $roles=Role::all();
        
        if($request->has('search')){
            $roles=Role::where('name','like',"%{$request->search}%")->get();
        }
        if(Gate::allows('is-admin')){

        return view('roles.index',compact("roles"));
    }
    dd('You Need To Be An Admin To Use This');

}
    public function create()
    {
        return view('roles.created');
       
    }
    public function Store(RoleStoreRequest $request,Role $role)
    {
        Role::create($request->validated());
        return redirect()->route('roles.index')->with('message','Role Added!')->with('message_status', 'success');     
    }
    public function edit(Role $role)
    {
        return view('roles.edit', compact('role'));
    }
    public function update(RoleUpdateRequest $request, Role $role)
    {
        $role->update([
            'name' => $request->name,
    
        ]);
        return redirect()->route('roles.index')->with('message','Role Updated!')->with('message_status', 'success');
    }
    public function destroy(Role $role)
    {
       
        $role->delete();
        return redirect()->route('roles.index')->with('message','Role Deleted');

    }
}

resources/views/roles/created.blade.php
@extends('layouts.main')
@section('content')
 <!-- Page Heading -->
 <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Roles</h1>    
</div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Add Role') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('roles.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.main')
@section('content')
 <!-- Page Heading -->
 <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Roles</h1>    
</div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Update Role') }}
                <a href="{{  route('roles.index')    }}" class="float-right">Back</a>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('roles.update',$role->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$role->name) }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
     
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update ') }}
                                </button>
                            </div>
                            
                        </div>
                        
                    </form>
                </div>
            </div>
           <div class="m-2 p-2">
           <form method="POST" action="{{route('roles.destroy',$role->id)}}"> 
                @csrf
                @method('DELETE')
                <button class="btn btn-danger">Delete This Role </button>
            </form>
           </div>
        </div>
        
    </div>
</div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.main')
@section('content')


 <!-- Page Heading -->
 <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Roles</h1>    
</div>
<div class="row">
<div class="card mx-auto">
        <div>@if (session()->has('message'))
            <div class="alert alert-success">
                {{session('message')}}
            </div>
            @endif
        </div>
    <div class="card-header"> 
        <div class="row">
            <div class="col">
                 <form method="GET" action="{{route('roles.index')}}">
                    <div class="form-row align-items-center">
                        <div class="col$">
                             <input type="search" name="search"class="form-control mb-2" id="inlineFormInput" placeholder="Search">
                        </div>
                    <div class="col">
                         <button type="submit" class="btn btn-primary mb-2">Search</button>
                 </div>
            </div>
            </form>
            </div>
            <div>
        <a href="{{route('roles.create')   }}" class="btn btn-primary mb-2">Add </a>
 
    </div>    
       
</div>
    </div>


  <div class="card body">
  <table class="table">
   <thead>
       <tr>
          <th scope="col" >Roles List</th>   
       </tr>
   </thead>
   <tbody>
          @foreach($roles as $role)
          <tr>
         
            <td> {{$role->name}}</td>
    
            
             <td>
                 <a href="{{route('roles.edit',$role->id)}}" class="btn btn-success">Edit</a>
            </td> 
         </tr>
         @endforeach
      </tbody>
  </table>
   </div>
  </div>
</div>
@endsection